Add models: ElasticNet, Ridge, Lasso and LinearSVC
lambdaclass/concrete-ml-fuzzer pull request #11
Opened 2023-04-17 18:58 UTC by Juan-M-V

2023-04-19 19:45 UTC, daphneherlambda requested changes
Just to keep the code uniform, add the comments in the linear_svc to all the fuzzers

2023-04-19 20:42 UTC, Juan-M-V commented
> Just to keep the code uniform, add the comments in the linear_svc to all the fuzzers

Resolved: https://github.com/lambdaclass/concrete-ml-fuzzer/pull/11/commits/6dfffc1b1847746840ff4193b93dc0a69c733fcc

2023-04-20 13:23 UTC, daphneherlambda approved these changes

2023-04-20 14:02 UTC, jrchatruc commented on src/elastic_net.py
> +
I think comments here should be one line below each, right?

2023-04-20 14:09 UTC, jrchatruc commented
Looks good other than my small comment

2023-04-20 14:09 UTC, jrchatruc approved these changes

2023-04-20 18:04 UTC, merged