Create Linear regression fuzzer
lambdaclass/concrete-ml-fuzzer pull request #6
Opened 2023-04-10 21:01 UTC by Juan-M-V

Implement fuzzer for linear regression model

2023-04-19 19:56 UTC, daphneherlambda requested changes
merge with main and we are ready to go!

2023-04-19 20:18 UTC, Juan-M-V commented
> merge with main and we are ready to go!

Resolved https://github.com/lambdaclass/concrete-ml-fuzzer/pull/6/commits/b4582fc5bcfd9f500827d2c0f58b00aa8da2dcf5 & https://github.com/lambdaclass/concrete-ml-fuzzer/pull/6/commits/be7e1df322ae5604d1e82e110ba2296e0ee47df9

2023-04-19 21:32 UTC, Oppen approved these changes

2023-04-20 13:26 UTC, daphneherlambda approved these changes

2023-04-20 13:26 UTC, merged